name: cristalyse
description: "Cristalyse is a high-performance data visualization library for Dart/Flutter that implements grammar of graphics principles with native rendering capabilities."
version: 0.4.1
homepage: https://github.com/rudi-q/cristalyse
repository: https://github.com/rudi-q/cristalyse
issue_tracker: https://github.com/rudi-q/cristalyse/issues
documentation: https://github.com/rudi-q/cristalyse#readme

topics:
  - data-visualization
  - charts
  - flutter-charts
  - plotting
  - analytics

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:



